# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caculate_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 330)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBox_num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.textBox_num1.setGeometry(QtCore.QRect(70, 90, 113, 71))
        self.textBox_num1.setObjectName("textBox_num1")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(220, 100, 91, 61))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.textBox_num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.textBox_num2.setGeometry(QtCore.QRect(350, 90, 113, 71))
        self.textBox_num2.setObjectName("textBox_num2")

        self.calculate_bottom = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_bottom.setGeometry(QtCore.QRect(510, 100, 171, 61))
        self.calculate_bottom.setCheckable(False)
        self.calculate_bottom.setObjectName("calculate_bottom")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.calculate_bottom.clicked.connect(self.calculate)  ########## 要加入這個讓 bottom有功能

    def calculate(self):
        # 讀取資料
        num1 = float(self.textBox_num1.text())
        num2 = float(self.textBox_num2.text())
        operator = self.comboBox.currentText()

        result = 0 #初始化結果
        stringBuilder = ""
        if operator == "":
            stringBuilder = f"請選擇運算符號"
        if operator == "+":
            result = num1 + num2
            stringBuilder = f"{num1} + {num2} = {result}"
        elif operator == "-":
            result = num1 - num2
            stringBuilder = f"{num1} - {num2} = {result}"
        elif operator == "*":
            result = num1 * num2
            stringBuilder = f"{num1} * {num2} = {result}"
        elif operator == "/":
            if num2 == 0 :
                result = "Error cuz num2 不能是 0"
            else:
                result = num1 / num2
                stringBuilder = f"{num1} / {num2} = {result}"
        # 顯示結果
        if result is not None:
            # QtWidgets.QMessageBox.information(MainWindow, "Result", str(result)) # 這是某一種顯示的寫法
            QtWidgets.QMessageBox.information(MainWindow, "result", stringBuilder)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(1, _translate("MainWindow", "+"))
        self.comboBox.setItemText(2, _translate("MainWindow", "-"))
        self.comboBox.setItemText(3, _translate("MainWindow", "*"))
        self.comboBox.setItemText(4, _translate("MainWindow", "/"))
        self.calculate_bottom.setText(_translate("MainWindow", "calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
