# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VolleyKindomForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VolleyKindomForm(object):
    def setupUi(self, VolleyKindomForm):
        VolleyKindomForm.setObjectName("VolleyKindomForm")
        VolleyKindomForm.resize(400, 244)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        VolleyKindomForm.setFont(font)
        self.Buttom_Im_player = QtWidgets.QPushButton(VolleyKindomForm)
        self.Buttom_Im_player.setGeometry(QtCore.QRect(40, 60, 121, 111))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Buttom_Im_player.setFont(font)
        self.Buttom_Im_player.setShortcut("")
        self.Buttom_Im_player.setCheckable(False)
        self.Buttom_Im_player.setObjectName("Buttom_Im_player")
        self.Buttom_Im_staff = QtWidgets.QPushButton(VolleyKindomForm)
        self.Buttom_Im_staff.setGeometry(QtCore.QRect(230, 60, 121, 111))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Buttom_Im_staff.setFont(font)
        self.Buttom_Im_staff.setShortcut("")
        self.Buttom_Im_staff.setCheckable(False)
        self.Buttom_Im_staff.setObjectName("Buttom_Im_staff")

        self.retranslateUi(VolleyKindomForm)
        QtCore.QMetaObject.connectSlotsByName(VolleyKindomForm)

    def retranslateUi(self, VolleyKindomForm):
        _translate = QtCore.QCoreApplication.translate
        VolleyKindomForm.setWindowTitle(_translate("VolleyKindomForm", "VolleyKindomForm"))
        self.Buttom_Im_player.setText(_translate("VolleyKindomForm", "報名臨打"))
        self.Buttom_Im_staff.setText(_translate("VolleyKindomForm", "工作人員"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VolleyKindomForm = QtWidgets.QWidget()
    ui = Ui_VolleyKindomForm()
    ui.setupUi(VolleyKindomForm)
    VolleyKindomForm.show()
    sys.exit(app.exec_())
